#!/usr/bin/env sh
# Commits apps/web/dist to the `site` branch with its provenance and checksums (D-064).
# Runs in CI after a green main; a deploy then copies `dist/` from that branch without building.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
source=${SOURCE:-$(git -C "$root" rev-parse HEAD)}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

git -C "$root" fetch --quiet origin site 2>/dev/null || true
if git -C "$root" rev-parse --verify --quiet origin/site >/dev/null; then
  git -C "$root" worktree add --quiet "$work/site" origin/site
  git -C "$work/site" checkout --quiet -B site
else
  git -C "$root" worktree add --quiet --detach "$work/site"
  git -C "$work/site" checkout --quiet --orphan site
fi
site="$work/site"
git -C "$site" rm -r --quiet --cached . 2>/dev/null || true
find "$site" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

cp -R "$root/apps/web/dist" "$site/dist"
(cd "$site/dist" && find . -type f ! -name SHA256SUMS | LC_ALL=C sort | xargs sha256sum) >"$site/SHA256SUMS"
cat >"$site/BUILD.md" <<INFO
# NextStroke web build

Generated by CI (scripts/publish_site.sh, D-064). Do not edit; deploy \`dist/\` as is.

- Source commit: $source
- Built: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Node: $(node --version)
- pnpm: $(pnpm --version)
- Check: \`cd dist && sha256sum -c ../SHA256SUMS\`
INFO

git -C "$site" add -A
if git -C "$site" diff --cached --quiet; then
  echo "site: no change"
else
  git -C "$site" -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    commit --quiet -m "Build of $source"
  git -C "$site" push --quiet origin site
  echo "site: published build of $source"
fi
git -C "$root" worktree remove --force "$site"
